/// Maps a BCP-47 language code to an ISO 3166-1 alpha-2 country code.
/// Used to display flag emojis next to language names.
String langToCountryCode(String lang) {
  final l = lang.toLowerCase().trim();
  const Map<String, String> _map = {
    'fr': 'fr',
    'en': 'gb',
    'en-us': 'us',
    'ja': 'jp',
    'zh': 'cn',
    'zh-hk': 'hk',
    'zh-tw': 'tw',
    'ko': 'kr',
    'es': 'es',
    'es-419': 'mx',
    'es-la': 'mx',
    'esla': 'mx',
    'es419': 'mx',
    'pt': 'pt',
    'pt-br': 'br',
    'ptbr': 'br',
    'pt-pt': 'pt',
    'ru': 'ru',
    'ar': 'sa',
    'de': 'de',
    'it': 'it',
    'pl': 'pl',
    'tr': 'tr',
    'vi': 'vn',
    'th': 'th',
    'id': 'id',
    'hi': 'in',
    'nl': 'nl',
    'sv': 'se',
    'fi': 'fi',
    'no': 'no',
    'nb-no': 'no',
    'da': 'dk',
    'cs': 'cz',
    'sk': 'sk',
    'ro': 'ro',
    'hu': 'hu',
    'bg': 'bg',
    'hr': 'hr',
    'sr': 'rs',
    'uk': 'ua',
    'he': 'il',
    'fa': 'ir',
    'ms': 'my',
    'fil': 'ph',
    'tl': 'ph',
    'bn': 'bd',
    'ta': 'in',
    'te': 'in',
    'kn': 'in',
    'ml': 'in',
    'mr': 'in',
    'gu': 'in',
    'pa': 'in',
    'ur': 'pk',
    'km': 'kh',
    'lo': 'la',
    'my': 'mm',
    'ka': 'ge',
    'hy': 'am',
    'az': 'az',
    'kk': 'kz',
    'ky': 'kg',
    'uz': 'uz',
    'tk': 'tm',
    'mn': 'mn',
    'si': 'lk',
    'ne': 'np',
    'af': 'za',
    'sw': 'ke',
    'yo': 'ng',
    'ig': 'ng',
    'ha': 'ng',
    'am': 'et',
    'so': 'so',
    'zu': 'za',
    'xh': 'za',
    'is': 'is',
    'ga': 'ie',
    'lv': 'lv',
    'lt': 'lt',
    'et': 'ee',
    'eu': 'es',
    'ca': 'es',
    'gl': 'es',
    'el': 'gr',
    'sq': 'al',
    'mk': 'mk',
    'bs': 'ba',
    'sl': 'si',
    'lb': 'lu',
    'mt': 'mt',
    'cy': 'gb',
    'gn': 'py',
    'ht': 'ht',
    'sm': 'ws',
    'fo': 'fo',
    'ku': 'iq',
    'sh': 'rs',
    'as': 'in',
  };
  return _map[l] ?? '';
}

/// Returns a flag emoji for a BCP-47 language code.
/// Falls back to 🌐 when no country mapping is found.
String langFlagEmoji(String lang) {
  final country = langToCountryCode(lang);
  if (country.length != 2) return '🌐';
  final codePoints = country.toUpperCase().codeUnits
      .map((u) => u - 0x41 + 0x1F1E6);
  return String.fromCharCodes(codePoints);
}

String completeLanguageName(String lang) {
  lang = lang.toLowerCase().trim();
  if (lang == 'multi' || lang == 'all' || lang == 'al') {
    return 'Multi-language';
  }
  for (var element in languagesMap.entries) {
    if (element.value.toLowerCase() == lang) {
      return element.key;
    }
  }
  return lang.toUpperCase();
}

final languagesMap = {
  'All': 'all',
  'Français': 'fr',
  'Català': 'ca',
  'English': 'en',
  'Tiếng Việt': 'vi',
  'ไทย': 'th',
  'Bulgaria': 'bg',
  'العربية': 'ar',
  'Português': 'pt',
  '한국어': 'ko',
  'Português (Brasil)': 'pt-br',
  'Italiano': 'it',
  'Pусский язык': 'ru',
  'Español': 'es',
  'Español (Latinoamérica)': 'es-419',
  'Español (Latinoamérica) ': 'es-la',
  'Indonesia': 'id',
  'हिन्दी, हिंदी': 'hi',
  '日本語': 'ja',
  'Polski': 'pl',
  'Türkçe': 'tr',
  'Deutsch': 'de',
  '中文(Zhōngwén)': 'zh',
  '繁體中文(Hong Kong)': 'zh-hk',
  "Filipino": "fil",
  "Ελληνικά": "el",
  "dansk": "da",
  "বাংলা": "bn",
  "Afrikaans": "af",
  "አማርኛ": "am",
  "Azərbaycan": "az",
  "беларуская": "be",
  "bosanski": "bs",
  "svenska": "sv",
  "suomi": "fi",
  "فارسی": "fa",
  "euskara": "eu",
  "Norwegian Bokmål (Norway)": "nb-no",
  "lietuvių kalba": "lt",
  "srpskohrvatski": "sh",
  "Norsk": "no",
  "עברית": "he",
  "Монгол": "mn",
  "മലയാളം": "ml",
  "Українська": "uk",
  "isiZulu": "zu",
  "isiXhosa": "xh",
  "Nederlands": "nl",
  "ဗမာစာ": "my",
  "Malaysia": "ms",
  "Hrvatski": "hr",
  "Română": "ro",
  "български": "bg",
  "čeština": "cs",
  "Kurdî": "ku",
  "Magyar": "hu",
  "Cebuano": "ceb",
  "English (United States)": "en-us",
  "Esperanto": "eo",
  "Estonian": "et",
  "Faroese": "fo",
  "Irish": "ga",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Hausa": "ha",
  "Haitian Creole": "ht",
  "Armenian": "hy",
  "Igbo": "ig",
  "Icelandic": "is",
  "Georgian": "ka",
  "Javanese": "jv",
  "Kazakh": "kk",
  "Cambodian": "km",
  "Kannada": "kn",
  "Kyrgyz": "ky",
  "Luxembourgish": "lb",
  "Laothian": "lo",
  "Latvian": "lv",
  "Malagasy": "mg",
  "Maori": "mi",
  "Macedonian": "mk",
  "Marathi": "mr",
  "Maltese": "mt",
  "Nepali": "ne",
  "Nyanja": "ny",
  "Pashto": "ps",
  "Portuguese (Portugal)": "pt-pt",
  "Romansh": "rm",
  "Sindhi": "sd",
  "Sinhalese": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Samoan": "sm",
  "Shona": "sn",
  "Somali": "so",
  "Albanian": "sq",
  "Serbian": "sr",
  "Sesotho": "st",
  "Swahili": "sw",
  "Tamil": "ta",
  "Tajik": "tg",
  "Tigrinya": "ti",
  "Turkmen": "tk",
  "Tonga": "to",
  "Urdu": "ur",
  "Yoruba": "yo",
  "Chinese (Traditional)": "zh-tw",
  "Latin": "la",
  "Uzbek": "uz",
  "Tagalog": "tl",
  'অসমীয়া': 'as',
};

/// this might not always work depending on how every extension provides its subtitles
String completeLanguageNameEnglish(String lang) {
  lang = lang.toLowerCase();
  for (var element in languagesMapEnglish.entries) {
    if (element.value.toLowerCase() == lang) {
      return element.key;
    }
  }
  return lang.trim().toUpperCase();
}

final languagesMapEnglish = {
  'All': 'all',
  'French': 'fr',
  'English': 'en',
  'Vietnamese': 'vi',
  'Thai': 'th',
  'Bulgaria': 'bg',
  'Arabian': 'ar',
  'Portuguese': 'pt',
  'Korean': 'ko',
  'Portuguese - Portuguese(Brazil)': 'pt-br',
  'Italian': 'it',
  'Russian': 'ru',
  'Spanish': 'es',
  'Spanish - Spanish(Latin_America)': 'es-la',
  'Indonesia': 'id',
  'Japanese': 'ja',
  'Polish': 'pl',
  'Turkish': 'tr',
  'German': 'de',
  'Chinese': 'zh',
  "Filipino": "fil",
  "dansk": "da",
  "Afrikaans": "af",
  "Azərbaycan": "az",
  "bosanski": "bs",
  "svenska": "sv",
  "suomi": "fi",
  "Norwegian Bokmål (Norway)": "nb-no",
  "Norsk": "no",
  "Nederlands": "nl",
  "Malaysia": "ms",
  "Hrvatski": "hr",
  "Kurdî": "ku",
  "Magyar": "hu",
  "Cebuano": "ceb",
  "English (United States)": "en-us",
  "Esperanto": "eo",
  "Estonian": "et",
  "Faroese": "fo",
  "Irish": "ga",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Hausa": "ha",
  "Haitian Creole": "ht",
  "Armenian": "hy",
  "Igbo": "ig",
  "Icelandic": "is",
  "Georgian": "ka",
  "Javanese": "jv",
  "Kazakh": "kk",
  "Cambodian": "km",
  "Kannada": "kn",
  "Kyrgyz": "ky",
  "Luxembourgish": "lb",
  "Laothian": "lo",
  "Latvian": "lv",
  "Malagasy": "mg",
  "Maori": "mi",
  "Macedonian": "mk",
  "Marathi": "mr",
  "Maltese": "mt",
  "Nepali": "ne",
  "Nyanja": "ny",
  "Pashto": "ps",
  "Portuguese (Portugal)": "pt-pt",
  "Romansh": "rm",
  "Sindhi": "sd",
  "Sinhalese": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Samoan": "sm",
  "Shona": "sn",
  "Somali": "so",
  "Albanian": "sq",
  "Serbian": "sr",
  "Sesotho": "st",
  "Swahili": "sw",
  "Tamil": "ta",
  "Tajik": "tg",
  "Tigrinya": "ti",
  "Turkmen": "tk",
  "Tonga": "to",
  "Urdu": "ur",
  "Yoruba": "yo",
  "Chinese (Traditional)": "zh-tw",
  "Latin": "la",
  "Uzbek": "uz",
  "Tagalog": "tl",
  "Assamese": "as",
};
